// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW20_NVhNP13vU3csZ7Q-tcZxmZJiauuU',
    appId: '1:961536727821:web:b3cc7a97128c8b3571ae44',
    messagingSenderId: '961536727821',
    projectId: 'attendance-64030',
    authDomain: 'attendance-64030.firebaseapp.com',
    storageBucket: 'attendance-64030.appspot.com',
    measurementId: 'G-CRHC8XZ0D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0FAnihLx56s6r_r6i4HfXfvpnBCvKccc',
    appId: '1:961536727821:android:90592ffa5b26d6c571ae44',
    messagingSenderId: '961536727821',
    projectId: 'attendance-64030',
    storageBucket: 'attendance-64030.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3lreoIbq6GBRYqJirWG9cFgudD5K3Uuo',
    appId: '1:961536727821:ios:0624bdb655fbc5a671ae44',
    messagingSenderId: '961536727821',
    projectId: 'attendance-64030',
    storageBucket: 'attendance-64030.appspot.com',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3lreoIbq6GBRYqJirWG9cFgudD5K3Uuo',
    appId: '1:961536727821:ios:0ce6185a314aa98c71ae44',
    messagingSenderId: '961536727821',
    projectId: 'attendance-64030',
    storageBucket: 'attendance-64030.appspot.com',
    iosBundleId: 'com.example.attendance.RunnerTests',
  );
}
